app_version: latest
capabilities: []
categories:
- media
date_added: '2025-10-07'
description: Nevu for Plex is an alternative UI for your personal Plex server, providing
  modern and immersive interfaces for Web, Desktop, Android and AndroidTV. Note that
  Nevu still requires you to have a Plex server that it can connect to - it's just
  a different interface running on a separate web server.
home: https://github.com/Ipmake/NevuForPlex
host_mounts: []
icon: https://media.sys.truenas.net/apps/nevu-for-plex/icons/icon.png
keywords:
- plex
- media
- ui
- alternative
- frontend
- streaming
lib_version: 2.1.57
lib_version_hash: 6659ad369fff2f1df318cb6353bb32bffe7047dc21df4823750d39be7284e605
maintainers:
- email: dev@truenas.com
  name: truenas
  url: https://www.truenas.com/
name: nevu-for-plex
run_as_context:
- description: Nevu for Plex runs as any non-root user.
  gid: 568
  group_name: nevu
  uid: 568
  user_name: nevu
screenshots: []
sources:
- https://github.com/Ipmake/NevuForPlex
- https://hub.docker.com/r/ipmake/nevu
title: Nevu for Plex
train: community
version: 1.3.2
