images:
  image:
    repository: ipmake/nevu
    tag: latest

consts:
  nevu_container_name: nevu-for-plex
  perms_container_name: permissions
  internal_web_port: 3000
  discovery_port: 44201
  discovery_port_config:
    bind_mode: published
    port_number: 44201
